development:
  adapter: postgresql
  encoding: unicode
  database: social
  pool: 5
  username: work
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: social
  pool: 5
  username: work
  password:
  timeout: 5000
